# Deployment.yaml.template
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 03f57369-8c7f-45a2-b14c-43cda86db7f2-nodejs-app
  namespace: local
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs
        image: /nodejs-image:latest
        ports:
        - containerPort: 3000
